In [2]:
import pandas as pd
import numpy as np

df = pd.read_csv('Titanic-Dataset.csv')              
tip = pd.read_csv('tip.csv')

In [ ]:
#aggeration
tip.groupby('day').agg(
    Bill_count=('total_bill', 'size'),
    avg_bill=('total_bill', 'mean'),
    avg_tip=('tip','mean')
)

      Bill_count   avg_bill   avg_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [8]:
tip.groupby('time').agg(
    bills=('total_bill', 'mean'),
    avg_bill=('total_bill', 'mean'),
    avg_party=('size','mean')
)

            bills   avg_bill  avg_party
time
Dinner  20.797159  20.797159   2.630682
Lunch   17.168676  17.168676   2.411765

In [ ]:
#table
summary = tip.groupby('day').agg(
    Bill_count=('total_bill', 'size'),
    avg_bill=('total_bill', 'mean'),
    avg_tip=('tip','mean')
)
summary

      Bill_count   avg_bill   avg_tip
day
Fri           19  17.151579  2.734737
Sat           87  20.441379  2.993103
Sun           76  21.410000  3.255132
Thur          62  17.682742  2.771452

In [12]:
summary[summary['day']=='Sun']
#it doesnt work because when we do groupby on something it gets converted to index(i.e it becomes a row)

KeyError: 'day'

In [ ]:
#columns in a list
print(summary.columns.tolist())
print(summary.index.to_list())

['Bill_count', 'avg_bill', 'avg_tip']
['Fri', 'Sat', 'Sun', 'Thur']

In [ ]:
#reset index
flat = summary.reset_index()
print(flat.columns.tolist())
flat.head()

['day', 'Bill_count', 'avg_bill', 'avg_tip']

    day  Bill_count   avg_bill   avg_tip
0   Fri          19  17.151579  2.734737
1   Sat          87  20.441379  2.993103
2   Sun          76  21.410000  3.255132
3  Thur          62  17.682742  2.771452

In [21]:
#make a new file names report
summary.to_csv('Report.csv')
flat = pd.read_csv('Report.csv')
flat.head()

    day  Bill_count   avg_bill   avg_tip
0   Fri          19  17.151579  2.734737
1   Sat          87  20.441379  2.993103
2   Sun          76  21.410000  3.255132
3  Thur          62  17.682742  2.771452

In [24]:
smoker_report = tip.groupby('smoker').agg(
    Bill_count=('total_bill', 'size'),
    avg_bill=('total_bill', 'mean'),
    avg_tip=('tip','mean')
)
smoker_report

        Bill_count   avg_bill   avg_tip
smoker
No             151  19.188278  2.991854
Yes             93  20.756344  3.008710

In [27]:
smoker_report.reset_index().to_csv('Smoker.csv')

In [34]:
#idx with max value
print(tip.groupby('day')['tip'].idxmax())
print(tip.groupby('day')['tip'].max())
print(tip.loc[183])

day
Fri      95
Sat     170
Sun     183
Thur    141
Name: tip, dtype: int64
day
Fri      4.73
Sat     10.00
Sun      6.50
Thur     6.70
Name: tip, dtype: float64
total_bill     23.17
tip              6.5
sex             Male
smoker           Yes
day              Sun
time          Dinner
size               4
Name: 183, dtype: object

In [37]:
b = pd.read_csv('bookings.csv')
print(b)

    booking_id        customer  day    time  party_size
0          101     ravi sharma  Sat  Dinner         4.0
1          102      PRIYA IYER  Sat  Dinner         2.0
2          103    Ravi Sharma   Sun   Lunch         NaN
3          104      amit kumar  Sun  Dinner         6.0
4          105     priya  iyer  Fri  Dinner         NaN
5          106     RAVI SHARMA  Sat   Lunch         3.0
6          107       sana khan  Sat   Lunch         NaN
7          108      Amit Kumar  Sat  Dinner         5.0
8          109      vikram rao  Sun  Dinner         2.0
9          110      Sana  Khan  Fri  Dinner         4.0
10         111      priya iyer  Sat   Lunch         NaN
11         112      VIKRAM RAO  Sun   Lunch         3.0

In [40]:
b['customer'].nunique()

12

In [43]:
print(b['customer'].str.lower().str.strip())

0     ravi sharma
1      priya iyer
2     ravi sharma
3      amit kumar
4     priya  iyer
5     ravi sharma
6       sana khan
7      amit kumar
8      vikram rao
9      sana  khan
10     priya iyer
11     vikram rao
Name: customer, dtype: object

In [48]:
b['customer'] = b['customer'].str.lower().str.strip().str.split().str.join(" ")
b['customer'].nunique()
print(b['customer'].unique().tolist())

['ravi sharma', 'priya iyer', 'amit kumar', 'sana khan', 'vikram rao']